routes/web.php
<?php

//auth
Route::group(["namespace" => "Auth"], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.store');
    Route::get('/register', 'RegisterController@showRegisterForm')->name('register');
    Route::post('/register', 'RegisterController@register')->name('register.store');
});

Route::group(["middleware" => "isActive"], function () {

    Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(["namespace" => "Web"], function () {
        // Route Home
        Route::resource('profile', 'User\ProfileController')->only('index', 'update');
        // Route Home
        Route::resource('home', 'Home\HomeController');
        Route::get('/', 'Home\HomeController@index');
        # User
        Route::resource('/data-user', 'User\UserController');
        Route::get('/data-user-paginate', 'User\UserController@paginate')->name('user.paginate');
        Route::get('/ajax-user', 'User\UserController@ajaxUser')->name('user.ajax');
        Route::get('/export-user', 'User\UserController@export')->name('user-export');

        // Route Configuration
        # Bab
        Route::group(["namespace" => "Konfigurasi"], function () {
            Route::resource('/config-admin', 'AdminController');
            Route::resource('/headline-news', 'HeadlineNewsController');
            Route::resource('/app-version', 'AppVersionController');
            Route::resource('config-wilayah', 'WilayahController')->only('index');
            Route::resource('config-province', 'ProvinceController');
            Route::get('/config-province-datatable', 'ProvinceController@datatable')->name('province.datatable');
            Route::resource('config-city', 'CityController');
            Route::get('/config-city-datatable', 'CityController@datatable')->name('city.datatable');
            Route::resource('config-district', 'DistrictController');
            Route::get('/config-district-datatable', 'DistrictController@datatable')->name('district.datatable');
            //smart school
            Route::resource('config-schools', 'SchoolController');
            Route::resource('config-book-categories', 'BookCategoryController');
            Route::resource('config-libraries', 'LibraryController');
        });

        Route::group(["namespace" => "SmartSchools", "middleware" => "isMySchoolActive"], function () {
            Route::resource('schools', 'SchoolController');
            Route::resource('school-years', 'SchoolYearController');
            Route::resource('school-generations', 'SchoolGenerationController');
            Route::resource('classes', 'ClassController');
            Route::resource('sub-classes', 'SubClassController');
            Route::resource('school-classes', 'SchoolClassController');
            Route::resource('school-students', 'StudentController');
            Route::resource('school-teachers', 'TeacherController');
            Route::resource('school-teacher-profiles', 'TeacherProfileController');
            Route::resource('school-subjects-categories', 'SubjectsCategoryController');
            Route::resource('school-subjects', 'SubjectsController');
            Route::resource('school-teacher-subjects', 'TeacherSubjectsController');
            Route::resource('school-class-subjects', 'ClassSubjectsController');
            Route::resource('school-schedules', 'ScheduleController');
            Route::resource('school-journals', 'JournalController');
            Route::resource('school-assessment-categories', 'AssessmentCategoryController');
            Route::resource('school-assessment-type-refs', 'AssessmentTypeRefController');
            Route::resource('school-assessment-types', 'AssessmentTypeController');
            Route::resource('school-academic-predicates', 'PredicateAcademicController');
            Route::resource('school-character-predicates', 'PredicateCharacterController');
            Route::resource('school-tasks', 'TaskController');
            Route::resource('school-task-questions', 'TaskQuestionController');
            Route::resource('school-task-corrections', 'TaskCorrectionController');
            Route::resource('school-task-results', 'TaskResultController');
            Route::resource('school-book-categories', 'BookCategoryController');
            Route::resource('school-libraries', 'LibraryController');
            Route::resource('school-teacher-files', 'TeacherFileController');
            Route::resource('school-rapors', 'RaporController');
            Route::resource('school-admins', 'AdminController');
            Route::resource('school-class-presences', 'ClassPresenceController');
            Route::resource('school-wall-magazines', 'WallMagazineController');
            Route::resource('school-announcements', 'AnnouncementController');
        });

        Route::group(['prefix' => 'laravel-filemanager'], function () {
            \UniSharp\LaravelFilemanager\Lfm::routes();
        });
    });

    Route::group(["namespace" => "Api"], function () {
        Route::post('/fcm-token', 'ApiFCMController@update')->name('fcm-token');
    });
});
Route::group(["namespace" => "Web\Konfigurasi"], function () {
    Route::get('/ajax-province', 'ProvinceController@ajaxProvince')->name('province.ajax');
    Route::get('/ajax-city', 'CityController@ajaxCity')->name('city.ajax');
    Route::get('/ajax-district', 'DistrictController@ajaxDistrict')->name('district.ajax');
});

resources/views/pages/smart_school/predicate/academic/create.blade.php
@extends('pages.home')
@section('content')
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                Form {{ $title }}
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="ibox-body">
                {{ Form::open(['id' => 'Create', 'route' => ['school-academic-predicates.store'], 'method' => 'POST', 'enctype' => 'multipart/form-data']) }}

                <div class="form-group">
                    {{ Form::label('', 'Batas Bawah', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('batas_bawah', null, ['class' => 'form-control', 'placeholder' => 'Gunakan titik "." untuk bilangan desimal']) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::label('', 'Batas Atas', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('batas_atas', null, ['class' => 'form-control', 'placeholder' => 'Gunakan titik "." untuk bilangan desimal']) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::label('', 'Deskripsi', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('deskripsi', null, ['class' => 'form-control', 'placeholder' => 'contoh : A, Baik, B, Cukup Baik']) }}
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                        Batal</button>
                    {{ Form::button('<i class="fa fa-save"></i> Tambah', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
                </div>
                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/smart_school/predicate/academic/edit.blade.php
@extends('pages.home')
@section('content')
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                Form {{ $title }}
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="ibox-body">
                {{ Form::open(['id' => 'Update', 'route' => ['school-academic-predicates.update', $data->id], 'method' => 'PATCH', 'enctype' => 'multipart/form-data']) }}

                <div class="form-group">
                    {{ Form::label('', 'Batas Bawah', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('batas_bawah', old('batas_bawah') ? old('batas_bawah') : $data->lower_limit, ['class' => 'form-control', 'placeholder' => 'Gunakan titik "." untuk bilangan desimal']) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::label('', 'Batas Atas', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('batas_atas', old('batas_atas') ? old('batas_atas') : $data->upper_limit, ['class' => 'form-control', 'placeholder' => 'Gunakan titik "." untuk bilangan desimal']) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::label('', 'Deskripsi', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('deskripsi', old('deskripsi') ? old('deskripsi') : $data->description, ['class' => 'form-control', 'placeholder' => 'contoh : A, Baik, B, Cukup Baik']) }}
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                        Batal</button>
                    {{ Form::button('<i class="fa fa-save"></i> Edit', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
                </div>
                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/smart_school/predicate/academic/index.blade.php
@extends('pages.home')
@section('content')
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">
            {{ $title }} |
            <a href="{{ route('school-academic-predicates.create') }}" class="btn btn-sm btn-outline-primary"><i class="fa fa-plus"></i> Buat {{$title}}</a>
        </div>
    </div>

    <div class="ibox-body">
        @include('flash')
        <table class="table table-striped table-bordered table-hover" id="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th width="10">No</th>
                    <th>Range</th>
                    <th>Predikat</th>
                    <th width="100">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($datas as $data)
                <tr>
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $data->lower_limit }} - {{ $data->upper_limit }}</td>
                    <td>{{ $data->description }}</td>
                    <td align="center">
                        <form id="{{$data->id}}" action="{{route('school-academic-predicates.destroy',$data->id)}}" method="post" style="display:inline">
                            @method('DELETE')
                            @csrf
                            <button onclick="return confirm('Perhatian! Menghapus Data ini akan menghapus data lainnya.')"  class="btn  btn-danger" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                        </form>
                        <a href="{{ route('school-academic-predicates.edit', $data->id) }}" class="btn btn-secondary"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection