routes/web.php
<?php

//auth
Route::group(["namespace" => "Auth"], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('login.store');
    Route::get('/register', 'RegisterController@showRegisterForm')->name('register');
    Route::post('/register', 'RegisterController@register')->name('register.store');
});

Route::group(["middleware" => "isActive"], function () {

    Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(["namespace" => "Web"], function () {
        // Route Home
        Route::resource('profile', 'User\ProfileController')->only('index', 'update');
        // Route Home
        Route::resource('home', 'Home\HomeController');
        Route::get('/', 'Home\HomeController@index');
        # User
        Route::resource('/data-user', 'User\UserController');
        Route::get('/data-user-paginate', 'User\UserController@paginate')->name('user.paginate');
        Route::get('/ajax-user', 'User\UserController@ajaxUser')->name('user.ajax');
        Route::get('/export-user', 'User\UserController@export')->name('user-export');

        // Route Configuration
        # Bab
        Route::group(["namespace" => "Konfigurasi"], function () {
            Route::resource('/config-admin', 'AdminController');
            Route::resource('/headline-news', 'HeadlineNewsController');
            Route::resource('/app-version', 'AppVersionController');
            Route::resource('config-wilayah', 'WilayahController')->only('index');
            Route::resource('config-province', 'ProvinceController');
            Route::get('/config-province-datatable', 'ProvinceController@datatable')->name('province.datatable');
            Route::resource('config-city', 'CityController');
            Route::get('/config-city-datatable', 'CityController@datatable')->name('city.datatable');
            Route::resource('config-district', 'DistrictController');
            Route::get('/config-district-datatable', 'DistrictController@datatable')->name('district.datatable');
            //smart school
            Route::resource('config-schools', 'SchoolController');
            Route::resource('config-book-categories', 'BookCategoryController');
            Route::resource('config-libraries', 'LibraryController');
        });

        Route::group(["namespace" => "SmartSchools", "middleware" => "isMySchoolActive"], function () {
            Route::resource('schools', 'SchoolController');
            Route::resource('school-years', 'SchoolYearController');
            Route::resource('school-generations', 'SchoolGenerationController');
            Route::resource('classes', 'ClassController');
            Route::resource('sub-classes', 'SubClassController');
            Route::resource('school-classes', 'SchoolClassController');
            Route::resource('school-students', 'StudentController');
            Route::resource('school-teachers', 'TeacherController');
            Route::resource('school-teacher-profiles', 'TeacherProfileController');
            Route::resource('school-subjects-categories', 'SubjectsCategoryController');
            Route::resource('school-subjects', 'SubjectsController');
            Route::resource('school-teacher-subjects', 'TeacherSubjectsController');
            Route::resource('school-class-subjects', 'ClassSubjectsController');
            Route::resource('school-schedules', 'ScheduleController');
            Route::resource('school-journals', 'JournalController');
            Route::resource('school-assessment-categories', 'AssessmentCategoryController');
            Route::resource('school-assessment-type-refs', 'AssessmentTypeRefController');
            Route::resource('school-assessment-types', 'AssessmentTypeController');
            Route::resource('school-academic-predicates', 'PredicateAcademicController');
            Route::resource('school-character-predicates', 'PredicateCharacterController');
            Route::resource('school-tasks', 'TaskController');
            Route::resource('school-task-questions', 'TaskQuestionController');
            Route::resource('school-task-corrections', 'TaskCorrectionController');
            Route::resource('school-task-results', 'TaskResultController');
            Route::resource('school-book-categories', 'BookCategoryController');
            Route::resource('school-libraries', 'LibraryController');
            Route::resource('school-teacher-files', 'TeacherFileController');
            Route::resource('school-rapors', 'RaporController');
            Route::resource('school-admins', 'AdminController');
            Route::resource('school-class-presences', 'ClassPresenceController');
            Route::resource('school-wall-magazines', 'WallMagazineController');
            Route::resource('school-announcements', 'AnnouncementController');
        });

        Route::group(['prefix' => 'laravel-filemanager'], function () {
            \UniSharp\LaravelFilemanager\Lfm::routes();
        });
    });

    Route::group(["namespace" => "Api"], function () {
        Route::post('/fcm-token', 'ApiFCMController@update')->name('fcm-token');
    });
});
Route::group(["namespace" => "Web\Konfigurasi"], function () {
    Route::get('/ajax-province', 'ProvinceController@ajaxProvince')->name('province.ajax');
    Route::get('/ajax-city', 'CityController@ajaxCity')->name('city.ajax');
    Route::get('/ajax-district', 'DistrictController@ajaxDistrict')->name('district.ajax');
});

app/Models/SmartSchools/School.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $fillable = [
        'name', 'jenjang', 'NPSN', 'NDS', 'total_students', 'address', 'district_id', 'village',
        'zip_code', 'fax', 'phone', 'website', 'email', 'headmaster', 'headmaster_nip',
        'headmaster_signature', 'logo', 'rapor_distribution', 
        'expired_at', 'created_by', 'updated_by', 'created_at', 'updated_at'
    ];

    public function students()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolStudent');
    }
    public function teachers()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolTeacher');
    }
    public function books()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolLibrary', 'school_id', 'id');
    }
    public function wall_magazines()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolWallMagazine', 'school_id', 'id');
    }
    public function district()
    {
        return $this->belongsTo('App\Models\Konfigurasi\District');
    }
    public function school_years()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolYear');
    }
    public function school_year()
    {
        return $this->school_years()->where('is_active', 1);
    }
    public function getHeadmasterSignatureAttribute($value)
    {
        if($value){
            return \Storage::disk('s3')->url($value);
        }
        return $value;
    }
    public function getHeadmasterSignatureBase64Attribute()
    {
        $value = $this->headmaster_signature;
        $result = null;
        if($value){
            $result = base64_encode(file_get_contents($value));
        }
        return $result;
    }
    public function getLogoAttribute($value)
    {
        if($value){
            return \Storage::disk('s3')->url($value);
        }
        return $value;
    }
    public function getSingkatanJenjangAttribute()
    {
        $words = explode(" ", $this->jenjang);
        $acronym = "";
        foreach ($words as $w) {
            $acronym .= $w[0];
        }
        return strtoupper($acronym);
    }
    public function getExpiredAtAttribute($value)
    {
        return date('d-M-Y', strtotime($value));
    }
}

app/Models/SmartSchools/SchoolAdmin.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolAdmin extends Model
{
    protected $fillable = [
        'school_id', 'user_id', 'created_at', 'updated_at'
    ];

    public function school()
    {
        return $this->belongsTo('App\Models\SmartSchools\School', 'school_id', 'id');
    }
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }
}

app/Models/SmartSchools/SchoolAnnouncement.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolAnnouncement extends Model
{
    protected $fillable = [
        'school_id', 'title', 'message', 'status', 'created_at', 'updated_at'
    ];

    protected $hidden = ['created_at', 'updated_at'];

    public function school()
    {
        return $this->belongsTo('App\Models\SmartSchools\School', 'school_id', 'id');
    }

    public function scopeSchoolId($query, $school_id)
    {
        return $query->where('school_id', $school_id);
    }
}

app/Models/SmartSchools/SchoolAssessmentCategory.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolAssessmentCategory extends Model
{
    protected $fillable = [
        'school_id', 'school_class_id', 'school_subjects_id', 
        'pengetahuan', 'keterampilan', 'sikap', 'created_at', 'updated_at'
    ];

    
    public function school()
    {
        return $this->belongsTo('App\Models\SmartSchools\School', 'school_id', 'id');
    }
    public function class()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolClassRef', 'school_class_id', 'id');
    }
    public function subjects()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolSubjects', 'school_subjects_id', 'id');
    }
    public function assessment_types()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolAssessmentType', 'assessment_category_id', 'id');
    }
}

app/Models/SmartSchools/SchoolAssessmentType.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolAssessmentType extends Model
{
    protected $fillable = [
        'school_id', 'assessment_category_id', 'assessment_type_ref_id', 'weight', 'created_at', 'updated_at'
    ];

    public function tasks()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolTasks');
    }
    public function assessment_category()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolAssessmentCategory', 'assessment_category_id', 'id');
    }
    public function assessment_type_ref()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolAssessmentTypeRef', 'assessment_type_ref_id', 'id');
    }

    public function scopeSchool($query, $school_id)
    {
        return null;
    }
}

app/Models/SmartSchools/SchoolAssessmentTypeRef.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolAssessmentTypeRef extends Model
{
    protected $fillable = [
        'school_id', 'category', 'name', 'created_at', 'updated_at'
    ];

    public function scopeSchool($query, $school_id)
    {
        return $query->where('school_id', $school_id);
    }
}

app/Models/SmartSchools/SchoolBookCategory.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolBookCategory extends Model
{
    protected $fillable = [
        'school_id', 'name', 'created_at', 'updated_at'
    ];

    protected $hidden = ['created_at', 'updated_at', 'school_id'];

    public function school()
    {
        return $this->belongsTo('App\Models\SmartSchools\School', 'school_id', 'id');
    }
    public function books()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolLibrary', 'category_id', 'id');
    }

    public function scopeSchoolId($query, $school_id)
    {
        return $query->where('school_id', $school_id);
    }
}

app/Models/SmartSchools/SchoolClass.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolClass extends Model
{
    protected $fillable = [
        'school_id', 'class_id', 'subclass_id', 'homeroom_teacher_id', 'created_at', 'updated_at'
    ];
    protected $appends = ['class_name'];
    protected $hidden = ['class', 'sub_class'];
    
    public function class()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolClassRef', 'class_id', 'id');
    }
    public function sub_class()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolSubclassRef', 'subclass_id', 'id');
    }
    public function school()
    {
        return $this->belongsTo('App\Models\SmartSchools\School', 'school_id', 'id');
    }
    public function homeroom()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolTeacher', 'homeroom_teacher_id', 'id');
    }
    public function subjects()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolTeacherSubjects', 'school_class_id', 'id');
    }
    public function all_students()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolStudentClass', 'class_id', 'id');
    }
    public function students()
    {
        return $this->all_students()->where('is_active', 1);
    }

    //scope
    public function scopeSchoolId($query, $school_id)
    {
        return $query->where('school_id', $school_id);
    }

    //accesor
    public function getClassNameAttribute()
    {
        return $this->class->name.' '.$this->sub_class->name;
    }
}

app/Models/SmartSchools/SchoolClassJournal.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolClassJournal extends Model
{
    protected $fillable = [
        'school_class_schedule_id', 'date', 'start_at', 'end_at', 'materi', 'note', 'created_at', 'updated_at'
    ];

    protected $dates = ['date'];
    
    public function class_schedule()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolClassSchedule', 'school_class_schedule_id', 'id');
    }
    public function student_presences()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolStudentPresence', 'school_class_journal_id', 'id');
    }
    public function getStudentPresenceDescriptionAttribute()
    {
        if($absen = $this->student_presences->whereNotIn('presence', ['H', 'T',])->count()){
            return $absen;
        }
        return 'Lengkap';
    }

    //scope
    public function scopeRole($query)
    {
        $school_id = mySchool();
        if(isset(auth()->user()->school_teacher->id) && !auth()->user()->hasPermissionTo('Semua Hak Akses')){
            $teacher_id = auth()->user()->school_teacher->id;
            return $query->whereHas('class_schedule.teacher_subjects.teacher', function($q) use($school_id, $teacher_id){
                $q->where('school_id', $school_id)->where('id', $teacher_id);
            });
        }elseif(auth()->user()->hasPermissionTo('Semua Hak Akses')){
            return $query->whereHas('class_schedule.teacher_subjects.teacher', function($q) use($school_id){
                $q->where('school_id', $school_id);
            });
        }
    }
    public function scopeThisYear($query)
    {
        $year = mySchoolYear();
        return $query->whereHas('class_schedule', function($q) use($year){
            $q->where('school_year_id', $year->id);
        });
    }
    //
    public function scopeSchoolId($query, $school_id)
    {
        return $query->whereHas('class_schedule.school_year', function($q) use($school_id){
            $q->where('school_id', $school_id);
        });
    }
    public function scopeClassId($query, $class_id)
    {
        return $query->whereHas('class_schedule.teacher_subjects', function($q) use($class_id){
            $q->where('school_class_id', $class_id);
        });
    }
    
    //acessor
    public function getStartAtAttribute($value)
    {
        return date('H:i', strtotime($value));
    }
    public function getStartAtTimeAttribute()
    {
        return strtotime($this->getOriginal('start_at'));
    }
    public function getEndAtAttribute($value)
    {
        return date('H:i', strtotime($value));
    }
}

app/Models/SmartSchools/SchoolClassRef.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolClassRef extends Model
{
    protected $fillable = [
        'school_id', 'name', 'created_at', 'updated_at'
    ];

    //scope
    public function scopeSchoolId($query, $school_id)
    {
        return $query->where('school_id', $school_id);
    }

    public function classes()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolClass', 'class_id', 'id');
    }
}

app/Models/SmartSchools/SchoolClassSubjects.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolClassSubjects extends Model
{
    protected $fillable = [
        'school_id', 'class_id', 'subjects_id', 'kkm', 'created_at', 'updated_at'
    ];

    protected $hidden = ['school_id', 'class_id', 'subjects_id', 'id'];
    
    public function subjects()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolSubjects', 'subjects_id', 'id');
    }
    public function class()
    {
        return $this->belongsTo('App\Models\SmartSchools\SchoolClassRef', 'class_id', 'id');
    }
    public function school()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolSchool', 'school_id', 'id');
    }
}

app/Models/SmartSchools/SchoolGeneration.php
<?php

namespace App\Models\SmartSchools;

use Illuminate\Database\Eloquent\Model;

class SchoolGeneration extends Model
{
    protected $fillable = [
        'school_id', 'year', 'created_at', 'updated_at'
    ];

    public function students()
    {
        return $this->hasMany('App\Models\SmartSchools\SchoolStudentClass', 'school_year_id', 'id');
    }
}

resources/views/pages/smart_school/subjects_category/create.blade.php
@extends('pages.home')
@section('content')
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                Form {{ $title }}
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="ibox-body">
                {{ Form::open(['id' => 'Create', 'route' => ['school-subjects-categories.store'], 'method' => 'POST', 'enctype' => 'multipart/form-data']) }}

                <div class="form-group">
                    {{ Form::label('', 'Kategori Mata Pelajaran', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('kategori_mata_pelajaran', null, ['class' => 'form-control', 'placeholder' => 'Muatan Nasional, Muatan Lokal Dll ']) }}
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                        Batal</button>
                    {{ Form::button('<i class="fa fa-save"></i> Tambah', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
                </div>
                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/smart_school/subjects_category/edit.blade.php
@extends('pages.home')
@section('content')
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                Form {{ $title }}
                </div>
            </div>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="ibox-body">
                {{ Form::open(['id' => 'Update', 'route' => ['school-subjects-categories.update', $data->id], 'method' => 'PATCH', 'enctype' => 'multipart/form-data']) }}

                <div class="form-group">
                    {{ Form::label('', 'Kategori Mata Pelajaran', ['class' => 'font-bold']) }}
                    <div class="input-group-icon left">
                        <div class="input-icon"><i class="fa fa-header text-info"></i></div>
                        {{ Form::text('kategori_mata_pelajaran', $data->name, ['class' => 'form-control', 'placeholder' => 'Muatan Nasional, Muatan Lokal Dll ']) }}
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                        Batal</button>
                    {{ Form::button('<i class="fa fa-save"></i> Edit', ['type' => 'submit', 'class' => 'btn btn-primary']) }}
                </div>
                {{ Form::close() }}

            </div>
        </div>
    </div>
</div>
<script>
$("#datepicker1").datepicker( {
    format: " yyyy", // Notice the Extra space at the beginning
    viewMode: "years",
    minViewMode: "years",
    orientation: "bottom"
});
$("#datepicker2").datepicker( {
    format: " yyyy", // Notice the Extra space at the beginning
    viewMode: "years",
    minViewMode: "years",
    orientation: "bottom"
});
</script>
@endsection

resources/views/pages/smart_school/subjects_category/index.blade.php
@extends('pages.home')
@section('content')
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">
            {{ $title }} |
            <a href="{{ route('school-subjects-categories.create') }}" class="btn btn-sm btn-outline-primary"><i class="fa fa-plus"></i> Buat {{$title}}</a>
        </div>
    </div>

    <div class="ibox-body">
        @include('flash')
        <table class="table table-striped table-bordered table-hover" id="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th width="10">No</th>
                    <th>Nama Mata Pelajaran</th>
                    <th width="100">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($datas as $data)
                <tr>
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $data->name }}</td>
                    <td align="center">
                        <!-- <form id="{{$data->id}}" action="{{route('school-subjects-categories.destroy',$data->id)}}" method="post" style="display:inline">
                            @method('DELETE')
                            @csrf
                            <button onclick="return confirm('Perhatian! Menghapus Data Tahun Angkatan akan menghapus data lainnya.')"  class="btn  btn-danger" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                        </form> -->
                        <a href="{{ route('school-subjects-categories.edit', $data->id) }}" class="btn btn-secondary"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection